name: Test embycon

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PR_TRIGGERED: ${{ github.event_name == 'pull_request' && github.repository == 'jellyfin/embycon' }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py_version: ['2.7', '3.9']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.py_version }}
        if: matrix.py_version != '2.7'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version }}

      - name: Set up Python 2.7
        if: matrix.py_version == '2.7'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python2.7 python2.7-dev python2-pip-whl
          sudo ln -sf python2.7 /usr/bin/python
          export PYTHONPATH=`echo /usr/share/python-wheels/pip-*py2*.whl`
          sudo --preserve-env=PYTHONPATH python -m pip install --upgrade pip setuptools wheel
          sudo chown -R $USER /usr/local/lib/python2.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --output-file=flake8.output
          cat flake8.output

      - name: Publish Test Atrifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 14
          name: ${{ matrix.py_version }}-test-results
          path: |
            flake8.output
